### PR TITLE
gcc-7.3: Fix include files for GCC 7

### PR DESCRIPTION
**Pull request by leon-anavi**
Using .inc files for GCC 9 by GCC 7 leads to issues with missing
omp.h while building UnifiedMemoryStreams from cuda-samples.
By porting apppropriate include files from release Thud of the
Yocto Project to the contrib sub-layer these issues are avoided.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Comment by madisongh** [comment]
Thanks!

**Comment by owenschris** [comment]
Thanks for finding this. Perhaps it should also be merged into the warrior branches? Same issue.

**Comment by leon-anavi** [comment]
@owenschris, thank you for the feedback. Sounds reasonable to me to apply the same changes in Warrior branches.

@madisongh would you like me to create a GitHub PR for warrior branches?

Best regards, Leon

**Comment by madisongh** [comment]
@leon-anavi If you have time to, then yes, that would be great.

**Comment by leon-anavi** [comment]
sure, pls give a couple of days to move these patches and tests them with builds from scratch before submitting the GitHub PR.

Best regards, Leon

**Comment by owenschris** [comment]
Cherry-pick of this commit along with the local.conf gcc7 changes from the wiki builds cuda-sample successfully on the warrior-l4t-32.2 branch. Thank you both!

**Comment by leon-anavi** [comment]
Hi @madisongh, @owenschris,

Following our discussion here I have created a couple of new GitHub PR for warrior branches:
https://github.com/madisongh/meta-tegra/pull/194
https://github.com/madisongh/meta-tegra/pull/195

Best regards, Leon

**Comment by madisongh** [comment]
Thanks @leon-anavi !  I've merged both of those PRs.

**Pull request merged**
