### PR TITLE
Kernel config fragments

### PR DESCRIPTION
**Pull request by mardy**
Submitting this for rocko: hopefully it's the right branch :-)

Anyway, I'm not a Yocto expert, so please review this carefully. The idea is taken from meta-raspberrypi, where a similar solution was adopted before.

### CODE REVIEW

**Comment by madisongh** [comment]
Pulling in the entire `linux-yocto.inc` file is too much - that file is really intended for kernels managed by the Yocto kernel team, or at least following the same basic pattern, which the NVIDIA kernel is most certainly not.

I'm OK with providing a way to make it easier to make kernel configuration changes in a `bbappend`, if that's the main goal here.  Perhaps something a bit simpler, though? I've personally always found the linux-yocto setup difficult to use.

**Comment by mardy** [comment]
Hi! So, what I need is a way to enable AppArmor in the kernel, from our `bbappend` file; do you know how other people have solved this issue before?

**Comment by philipc** [comment]
I'm not familiar with meta-raspberrypi, but it seems to be using [`kernel_configure_variable`](http://git.yoctoproject.org/cgit.cgi/meta-raspberrypi/tree/recipes-kernel/linux/linux-raspberrypi.inc#n46) to add the config changes to `CONF_SED_SCRIPT`, instead of using config fragments, whereas your PR is trying to use `CONF_SED_SCRIPT` without actually defining it?

The meta-raspberrypi approach can probably be made to work, but if you want to use config fragments, then I think all you need is the `merge_config.sh` command from [here](https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/kernel-yocto.bbclass#n312), but use a list of config fragments defined in the `bbappend` instead of what `kernel-yocto.bbclass` does. Either way, `linux-yocto.inc` shouldn't be needed.

**Comment by mardy** [comment]
I found a way to do it without touching the meta-tegra layer and contain all the changes in my bbappend:

```# Find config path
FILESEXTRAPATHS_append := ":${THISDIR}/files"

# Kernel configs
SRC_URI += " file://apparmor.cfg"

kernel_do_configure_prepend() {
    config_flags="-m"
    configs="${B}/.config ${WORKDIR}/apparmor.cfg"
    PATH=${S}/scripts/kconfig:${PATH}
    CFLAGS="${CFLAGS} ${TOOLCHAIN_OPTIONS}" HOSTCC="${BUILD_CC} ${BUILD_CFLAGS} ${BUILD_LDFLAGS}" HOSTCPP="${BUILD_CPP}" CC="${KERNEL_CC}" ARCH=${ARCH} merge_config.sh -O ${B} ${config_flags} ${configs} > ${B}/merge_config_build.log 2>&1
    if [ $? -ne 0 ]; then
        bbfatal_log "Could not configure ${KMACHINE}-${LINUX_KERNEL_TYPE}"
    fi
}
```
If you think that this is the right way to do it, then feel free to close this issue. :-)

**Pull request closed without merging**
