### PR TITLE
WIP: update to L4T R32.4.3/JetPack 4.4 GA

### PR DESCRIPTION
**Pull request by madisongh**
Work in progress.

Tested so far on Xavier NX dev kit, Nano dev kit, Jetson-TX2 (unsecured and secured):
* sato images build and boot
* basic gstreamer plugins working - nvarguscamerasrc, v4l2src, nvvidconv, nv3dsink
* basic CUDA tests (deviceQuery, UnifiedMemoryStreams) working
* Vulkan sample programs work
* L4T graphics demos work
* HDMI audio works
* NVIDIA docker containers work

More platforms and tests coming.

Note that JetPack Debian package downloads are a bit iffy at the moment, as NVIDIA straightens out their upgrade issues.

### CODE REVIEW

**Comment by kekiefer** [comment]
Working through t194 (xavier-8gb) build right now. Here's one patch:

```
From a553aa162fa1fc8597918c8574bfe228a74926fc Mon Sep 17 00:00:00 2001
From: Kurt Kiefer <kurt.kiefer@arthrex.com>
Date: Fri, 10 Jul 2020 09:44:52 -0700
Subject: [PATCH 1/1] tegra-helper-scripts: fix syntax error in t194 build

| DEBUG: Executing shell function do_deploy
| ./tegra194-flash-helper.sh: line 304: syntax error near unexpected token `else'
| ./tegra194-flash-helper.sh: line 304: `    else'
---
 .../tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh | 1 -
 1 file changed, 1 deletion(-)

diff --git a/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh b/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
index bd71991..fe7ceb9 100644
--- a/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
+++ b/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
@@ -300,7 +300,6 @@ else
 	    rm -f "$datafile"
 	    $here/mksparse -b ${blocksize} --fillpattern=0 "$dataimg" "$datafile" || exit 1
 	fi
-    fi
     else
 	tfcmd=${flash_cmd:-"flash;reboot"}
     fi
-- 
2.17.1
```

**Comment by madisongh** [comment]
Thanks, @kekiefer

**Comment by kekiefer** [comment]
Ack. Now that I've actually got through the build so I could use this to flash the device, I see that this was the wrong fix. `tfcmd` still needs to be set, the condition that got removed here was the check for keyfile. Here's a new patch that does flash the device:

```
From 2dfa21f44503bb3ba267283096e9409c538f8791 Mon Sep 17 00:00:00 2001
From: Kurt Kiefer <kurt.kiefer@arthrex.com>
Date: Fri, 10 Jul 2020 09:44:52 -0700
Subject: [PATCH 1/1] tegra-helper-scripts: fix syntax error in t194 build

| DEBUG: Executing shell function do_deploy
| ./tegra194-flash-helper.sh: line 304: syntax error near unexpected token `else'
| ./tegra194-flash-helper.sh: line 304: `    else'
---
 .../tegra-helper-scripts/tegra194-flash-helper.sh             | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

diff --git a/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh b/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
index bd71991..3ca0612 100644
--- a/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
+++ b/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
@@ -301,9 +301,7 @@ else
 	    $here/mksparse -b ${blocksize} --fillpattern=0 "$dataimg" "$datafile" || exit 1
 	fi
     fi
-    else
-	tfcmd=${flash_cmd:-"flash;reboot"}
-    fi
+    tfcmd=${flash_cmd:-"flash;reboot"}
 fi
 
 if [ -n "$keyfile" ]; then
-- 
2.17.1
```

**Comment by madisongh** [comment]
Thanks again, @kekiefer.  I've rebased the branch to pull in those changes as fixups and have added a U-Boot change to align with the R32.4.3 settings for the environment block location.

Basics are still working across the different Jetsons.  Issues I'm seeing currently:
 * [argus_camera segfault](https://forums.developer.nvidia.com/t/l4t-r32-4-3-breaks-argus-camera-and-causes-segmentation-fault-sigsegv/141432).  I'll keep an eye on that forum thread.
* Bluetooth not coming up on TX1 and TX2.  Appears to work OK with the L4T Ubuntu, but not for our builds.

**Pull request merged**
