### PR TITLE
Change module loading to prepend instead of set.

### PR DESCRIPTION
**Pull request by dljsjr**
Changes kernel module load in the include files to prepend instead of set. This allows for appending to these variables in the `local.conf` without needing to create a new layer.

### CODE REVIEW

**Comment by madisongh** [comment]
How about just using `<variable>_append` in your `local.conf` file to make additions?

**Comment by dljsjr** [comment]
I tried that and it didn't seem to work, I may have had a typo though.

**Comment by madisongh** [comment]
Yeah, give it another try.  It should work.  Don't forget to include a leading space in the string.

**Comment by dljsjr** [comment]
Yeah it's working, I accidentally typed `KERNEL_MODULES` not `MODULE` 😅

**Pull request closed without merging**
